---
# Main inventory for all managed hosts.
# In Semaphore: set inventory type to "File" and path to "inventory/hosts.yml".
#
# ansible_user must match the user created by first-installation/users/users.yml.
# The SSH private key is managed by Semaphore's Key Store (maintenance-ssh-key).

all:
  vars:
    ansible_user: maintenance
    ansible_python_interpreter: /usr/bin/python3

  children:
    vms:
      hosts:
        test:
          ansible_host: 192.168.100.240
#        pve02:
#          ansible_host: 192.168.x.x


    # Add your hosts here, grouped as needed.
    # Example:
    #
    # proxmox:
    #   hosts:
    #     pve01:
    #       ansible_host: 192.168.x.x
    #     pve02:
    #       ansible_host: 192.168.x.x
    #
    # docker:
    #   hosts:
    #     docker01:
    #       ansible_host: 192.168.x.x
