---
- name: Install packages
  ansible.builtin.apt:
    name:
      - prometheus-node-exporter
      - nfs-common
      - qemu-guest-agent
      - hdparm
      - inxi
      - htop
      - mosh
      - whois
      - nmap
      - iperf
      - apcupsd
      - apcupsd-doc
      - intel-microcode
      - iucode-tool
      - net-tools
    update_cache: true

- name: Start guest qemu-guest-agent
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true

- name: NTP Server
  timesync_ntp_servers:
      - hostname: docker-ntp.realise.ch
        pool: yes
        iburst: yes
        nts: yes

