---
- name: Update all packages to the latest version.
  ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 3600
      name: "*"
      state: latest

- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Reboot the server (if required).
  ansible.builtin.reboot:
    reboot_timeout: 300
    test_command: ping -c 4 192.168.100.3
  when: reboot_required_file.stat.exists == true

- name: Remove dependencies that are no longer required.
  ansible.builtin.apt:
    autoremove: yes